services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IchHabRecht\SocialGdpr\:
        resource: '../Classes/*'

#    IchHabRecht\SocialGdpr\Form\CustomInlineControl\OnlineFalMediaPreviewFlush:
#        tags:
#            -   name: event.listener
#                identifier: 'socialgdprModifyFileReferenceControlsEvent'
#                event: TYPO3\CMS\Backend\Form\Event\ModifyFileReferenceControlsEvent
#                method: renderFileReferenceHeaderControl

